fastfood/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('food/',include('food.urls',namespace='food')),

]

food/urls.py
from django.urls import path

from . import views

app_name = 'food'

urlpatterns = [
    path('pizza',views.pizza,name="pizzas"),
    path('burgers',views.burgers,name='burgers'),
    path('order',views.order,name="order"),
    path('success',views.success,name="success"),
    path('signup',views.signup,name="signup"),
    path('login',views.logIn,name="login"),
    path('logout',views.logOut,name="logout"),
]
 

food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    pImage = models.URLField()

class Burger(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    bImage = models.URLField()

class Order(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    number = models.CharField(max_length=60)
    bill = models.DecimalField(max_digits=4,decimal_places=2);
    date = models.DateTimeField(auto_now_add=True,blank=True)
    note = models.TextField(blank=True,null=True)

class Item(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    size = models.CharField(max_length=60)

food/forms.py
import email
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

class NewUserForm(UserChangeForm):
    email = forms.EmailField(max_length=100,required=True,help_text="Inform a valid email address")
    class Meta:
        model = User
        fields = ['username','email']

food/views.py
import json
from multiprocessing import AuthenticationError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pizza,Burger,Order,Item
from .forms import NewUserForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
import random
import json   

from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def randomOrderNumber(length):
    sample = 'ABCDEFGH0123456789'
    number0 = ''.join((random.choice(sample) for i in range(length)))
    return number0

def index(request):
    request.session.set_expiry(0)
    ctx = {'active_link': 'index'}
    return render(request, 'food/index.html',ctx)

def pizza(request):
    request.session.set_expiry(0)
    pizzas = Pizza.objects.all()
    ctx = {'pizzas':pizzas,'active_link': 'pizza'}
    return render(request, 'food/pizza.html',ctx)

def burgers(request):
    request.session.set_expiry(0)
    burgers = Burger.objects.all()
    ctx = {'burgers':burgers,'active_link': 'burger'}
    return render(request, 'food/burgers.html',ctx)

@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
       request.session['note'] = request.POST.get('note')
       request.session['order'] = request.POST.get('orders')
       orders = json.loads(request.session['order'])
       request.session['bill'] = request.POST.get('bill')
       randomNum = randomOrderNumber(6);

       while Order.objects.filter(number=randomNum).count() > 0:
            randomNum = randomOrderNumber(6)

       if request.user.is_authenticated:
            order = Order(customer=request.user,
                            number = randomNum,
                            bill = float(request.session['bill']),
                            note = request.session['note'])
            order.save()
            request.session['orderNum'] = order.number
            for article in orders:
                item = Item(
                    order = order,
                    name = article[0],
                    price = float(article[2]),
                    size = article[1]
                )
                item.save()

    ctx = {'active_link': 'order'}
    return render(request, 'food/order.html',ctx)

def success(request):
    orderNum =request.session['orderNum']
    bill = request.session['bill']
    items = Item.objects.filter(order__number = orderNum)
    ctx = {'orderNum':orderNum, 'bill':bill, 'items':items}
    return render(request, 'food/success.html',ctx)

def signup(request):
    ctx = {}
    if request.POST:
        form =  UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form'] = form
    else:
        form = UserCreationForm()
        ctx['form'] = form
    return render(request,'food/signup.html',ctx)

def logIn(request):
    if request.POST:
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(request, username=username,password = pwd)
        if user is not None:
            login(request,user)
            return redirect('index')
        else:
            messages.info(request,'username or password are incorrect')
    ctx={'active_link': 'login'}
    return render(request,'food/login.html',ctx)

def logOut(request):
    logout(request)
    return redirect('index')

food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="https://img.icons8.com/cotton/40/000000/beefburger.png">
    <title>{% block title %} {% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="https://img.icons8.com/cotton/40/000000/beefburger.png" class="logo "/>
        </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav" aria-controls="mynav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynav">
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'index' %}active{% endif %}" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}" href="{% url 'food:pizzas' %}">Pizzas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'burger' %}active{% endif %}" href="{% url 'food:burgers' %}">Burgers</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="navbar-brand mt-2">
              <h5 class="text-light pt-2 pr-4">Welcome {{ user.username }}</h5>
            </li>
          {% endif %}
          <li class="navbar-brand mt-2">
            <a href="{% url 'food:order' %}" class="navlink {% if active_link == 'order' %}active{% endif %}"><img src="https://img.icons8.com/fluency/30/undefined/shopping-cart.png"/><span id="cart"></span></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'food:logout' %}" class="nav-link"><img class="bg-light ml-2 rounded-circle" src="https://img.icons8.com/pastel-glyph/30/undefined/gender-neutral-user.png"/><br>Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'food:login' %}" class="nav-link {% if active_link == 'order' %}active{% endif %}"><img class="bg-light ml-2 rounded-circle" src="https://img.icons8.com/pastel-glyph/30/undefined/gender-neutral-user.png"/><br>Log-in</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

      <div>
       {% block content %} {% endblock %}
      </div>

    <!-- jQuery library -->
    <!--  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script> -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <script src="{% static 'food/js/main.js' %}"></script>
</body>
</html>


food/templates/food/burgers.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Burgers{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row ">
            <div class="col-md-8 text-center">
                <h2 class="title">Our Burgers</h2>
                <div class="row">
                    {% for burger in burgers %}
                    <div class="col-md-4 p-4 prod">
                        <img class="picture" src="{{ burger.bImage }}">
                        <h4 class="pt-3" id="bur{{burger.id}}"> {{ burger.name }} </h4>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="burger{{burger.id}}" value="{{burger.priceM}}" checked>
                               M: {{ burger.priceM }} $
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="burger{{burger.id}}" value="{{burger.priceL}}">
                               L: {{ burger.priceL }} $
                            </label>
                        </div>
                        <div>
                            <button class="btn-info mt-3" onclick="addBurger('{{ burger.id }}')">Add to cart</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 orders">
                <div class="bg-dark p-4 rounded text-light">
                    <h2 class = "text-center" >Order list</h2>
                    <ul id="bcart"></ul>
                    <h4 class="text-right" id="btotal">Total: 0 $</h4>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'food/js/border.js' %}"></script>
    
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="home"></div>

{% endblock %}

food/templates/food/login.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-6 p-4 bg-dark text-light text-center">
                <h3>Login</h3>
                <a href="{% url 'food:signup' %}">Sign Up</a>
                <form method="POST" class="p-2">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="username" placeholder="Username">                
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" placeholder="********">                 
                    </div>
                    
                    <button type="submit" class="btn-info">Login</button>
                    {% if messages %}
                        <ul class="pt-2 text-center">
                            {% for msg in messages %}
                            <li style="color: red;">{{ msg }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock %}

food/templates/food/order.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Order{% endblock %}

{% block content %}

    <div class="container-fluid m-4">
        {% if user.is_authenticated %}
            <h2>Welcome {{ user.username }}</h2>
        {% endif %}
        <div  class="row">
            <div class="col-md-7 text-center">
                <h2>Order</h2>
                <div class="row">
                    <div class="col-md-3" id="name">
                        <h3>Name</h3>
                    </div>
                    <div class="col-md-3" id="size">
                        <h3>Size</h3>
                    </div>
                    <div class="col-md-3" id="price">
                        <h3>Price</h3>
                    </div>
                    <div class="col-md-1" id="rm">
                        <h3>Price</h3>
                    </div>
                </div>
                <h2 id="total">Total:</h2>
            </div>
            <div class="col-md-5 mt-4">
                <h2>Message</h2>
                <textarea name="message" id="message" cols="40" rows="5"></textarea>
                {% if user.is_authenticated %}
                    <div class="ml-auto m-4">
                        <button type="submit" class="btn-success" onclick="order()">Submit</button>
                    </div>
                {% else %}
                    <div class="ml-auto m-4">
                       <a href="{% url 'food:login' %}">Log In</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script src="{% static 'food/js/cart.js' %}"></script>

{% endblock %}

food/templates/food/pizza.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}pizzas{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row ">
            <div class="col-md-8 text-center">
                <h2 class="title">Our pizzas</h2>
                <div class="row">
                    {% for pizza in pizzas %}
                    <div class="col-md-4 col-sm-6 p-4">
                        <img class="picture" src="{{ pizza.pImage }}">
                        <h4 class="pt-3" id="piz{{pizza.id}}" > {{ pizza.name }} </h4>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="pizza{{pizza.id}}"  value="{{pizza.priceM}}" checked>
                                M: {{ pizza.priceM }} $
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="pizza{{pizza.id}}" value="{{pizza.priceL}}">
                                L: {{ pizza.priceL }} $
                            </label>
                        </div>
                        <div>
                            <button class="btn-info mt-3" onclick="addPizza('{{ pizza.id }}')">Add to cart</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 orders">
                <div class="bg-dark p-4 rounded text-light">
                    <h2 class = "text-center" >Order list</h2>
                    <ul id="pcart"></ul>
                    <h4 class="text-right" id="ptotal">Total: 0 $</h4>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'food/js/order.js' %}"></script>
    
{% endblock %}

food/templates/food/signup.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Signup{% endblock %}

{% block content %}
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-6 p-4 bg-dark text-light text-center">
                <h3>Signup</h3>
                <a href="{% url 'food:login' %}" class="p-2">Log In</a>
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <div>
                            {{ field.label_tag }}
                        </div>
                        <div>
                            {{ field }}
                        </div>
                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        
                    </div>
                    {% endfor %}
                    <div>
                        {% for error in form.errors %}
                            <small style="color: red"> {{ error }}</small>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn-info">Signup</button>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock %}

food/templates/food/success.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Success{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h2>We have received your order</h2>
        <h4>Number of order: {{ orderNum }}</h4>
        <h4>You have ordered:</h4>
        {% for item in items %}
            <h4>{{ item.name }} {{ item.size }} {{ item.price }}</h4>
        {% endfor %}
        <h4>Total: {{ bill }} $</h4>
        <h4>If you want to modify your order,please call us</h4>
        <h4>Phone: 00 99 55 33 55</h4>
    </div>
{% endblock %}